CREATE TABLE SUPPLIER(
SID VARCHAR(20) PRIMARY KEY,
SNAME VARCHAR(30) NOT NULL,
SADDR VARCHAR(50) NOT NULL,
SCITY VARCHAR(20) CONSTRAINT CHECK_CITY CHECK (SCITY='DELHI'),
PHONE VARCHAR(15) CONSTRAINT UNQ_PHONE UNIQUE ,
EMAIL VARCHAR(30);
);
