CREATE TABLE STOCK(
PID VARCHAR(30) CONSTRAINT FK_STOCK_INFO REFERENCES PRODUCT(PID),
SQTY INT CONSTRAINT CHK_QTY CHECK (SQTY >=0),
ROL INT CONSTRAINT CHK_ROL CHECK (ROL >0),
MOQ INT CONSTRAINT CHK_MOQ CHECK (MOQ >=5)
);
