CREATE TABLE CUST(
CID VARCHAR(20) PRIMARY KEY,
CNAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(20) NOT NULL,
PHONE VARCHAR(15) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
DOB DATE CONSTRAINT CHK_DATE CHECK(DOB < '2000-01-01'));
