CREATE TABLE ORDERS(
OID VARCHAR(20),
ODATE DATE,
PID VARCHAR(30) CONSTRAINT FK_PRODUCT_INFO REFERENCES PRODUCT(PID),
CID VARCHAR (20) CONSTRAINT FK_KEY_CUST_INFO REFERENCES CUST(CID),
OQTY INT CONSTRAINT CHK_OQTY CHECK(OQTY>=1));
