CREATE TABLE PRODUCT(
PID VARCHAR(30) PRIMARY KEY,
PDESC VARCHAR(30) NOT NULL,
PRICE INT CONSTRAINT CHECK_PRICE CHECK (PRICE > 0 ),
CATEGORY VARCHAR(20) CONSTRAINT CHK_CATEGORY CHECK (CATEGORY IN ('IT','HR','HC')),
SID VARCHAR(20) CONSTRAINT FK_PRODUCT_SUPPLIER REFERENCES SUPPLIER(SID)
);
